
package com.onpe.sisveap.proxyws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DistribucionService", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DistribucionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarVerificadorOTS", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarVerificadorOTS")
    @ResponseWrapper(localName = "asignarVerificadorOTSResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarVerificadorOTSResponse")
    public String asignarVerificadorOTS(
        @WebParam(name = "arg0", targetNamespace = "")
        List<OrdenTrabajo> arg0)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.onpe.sisveap.proxyws.OrdenTrabajo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarOrdenTrabajo", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarOrdenTrabajo")
    @ResponseWrapper(localName = "listarOrdenTrabajoResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarOrdenTrabajoResponse")
    public List<OrdenTrabajo> listarOrdenTrabajo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.onpe.sisveap.proxyws.ArchivoOT
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerArchivoOT", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ObtenerArchivoOT")
    @ResponseWrapper(localName = "obtenerArchivoOTResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ObtenerArchivoOTResponse")
    public ArchivoOT obtenerArchivoOT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarSupervisorArchivoOT", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarSupervisorArchivoOT")
    @ResponseWrapper(localName = "asignarSupervisorArchivoOTResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarSupervisorArchivoOTResponse")
    public String asignarSupervisorArchivoOT(
        @WebParam(name = "arg0", targetNamespace = "")
        ArchivoOT arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.onpe.sisveap.proxyws.OrdenTrabajo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarOrdenTrabajoPorRegion", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarOrdenTrabajoPorRegion")
    @ResponseWrapper(localName = "listarOrdenTrabajoPorRegionResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarOrdenTrabajoPorRegionResponse")
    public List<OrdenTrabajo> listarOrdenTrabajoPorRegion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarVerificadorOT", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarVerificadorOT")
    @ResponseWrapper(localName = "asignarVerificadorOTResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.AsignarVerificadorOTResponse")
    public String asignarVerificadorOT(
        @WebParam(name = "arg0", targetNamespace = "")
        OrdenTrabajo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.onpe.sisveap.proxyws.OrdenTrabajo
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerOT", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ObtenerOT")
    @ResponseWrapper(localName = "obtenerOTResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ObtenerOTResponse")
    public OrdenTrabajo obtenerOT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.onpe.sisveap.proxyws.ArchivoOT>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarArchivoOT", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarArchivoOT")
    @ResponseWrapper(localName = "listarArchivoOTResponse", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", className = "com.onpe.sisveap.proxyws.ListarArchivoOTResponse")
    public List<ArchivoOT> listarArchivoOT();

}
