
package com.onpe.sisveap.proxyws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DistribucionService", targetNamespace = "http://distribucion.service.gepsac.sacooliveros.com/", wsdlLocation = "file:/D:/UPC/Harold/PI/fuentes/onpe-sisveap/sisveap/sisveap-proxyws/src/wsdl/DistribucionService.xml")
public class DistribucionService_Service
    extends Service
{

    private final static URL DISTRIBUCIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.onpe.sisveap.proxyws.DistribucionService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.onpe.sisveap.proxyws.DistribucionService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/UPC/Harold/PI/fuentes/onpe-sisveap/sisveap/sisveap-proxyws/src/wsdl/DistribucionService.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/UPC/Harold/PI/fuentes/onpe-sisveap/sisveap/sisveap-proxyws/src/wsdl/DistribucionService.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DISTRIBUCIONSERVICE_WSDL_LOCATION = url;
    }

    public DistribucionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistribucionService_Service() {
        super(DISTRIBUCIONSERVICE_WSDL_LOCATION, new QName("http://distribucion.service.gepsac.sacooliveros.com/", "DistribucionService"));
    }

    /**
     * 
     * @return
     *     returns DistribucionService
     */
    @WebEndpoint(name = "DistribucionServicePort")
    public DistribucionService getDistribucionServicePort() {
        return super.getPort(new QName("http://distribucion.service.gepsac.sacooliveros.com/", "DistribucionServicePort"), DistribucionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistribucionService
     */
    @WebEndpoint(name = "DistribucionServicePort")
    public DistribucionService getDistribucionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://distribucion.service.gepsac.sacooliveros.com/", "DistribucionServicePort"), DistribucionService.class, features);
    }

}
